import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}", "./public/page.json"],
  safelist: [
    // Dynamic accent colors from AI-generated page.json
    "bg-[#FF2D55]",
    "bg-[#00FF9D]",
    "bg-[#FF6675]",
    "bg-[#6A001A]",
    "text-[#FF2D55]",
    "text-[#00FF9D]",
    "text-[#FF6675]",
    "text-[#6A001A]",
    // Rotate classes
    "-rotate-1",
    "-rotate-2",
    "rotate-1",
    "rotate-2",
    // BG classes used in facts/badges
    "bg-primary",
    "bg-primary-container",
    "bg-secondary",
    "bg-secondary-container",
    "bg-tertiary-container",
    "text-primary",
    "text-white",
    "text-secondary-container",
    "text-on-surface-variant",
  ],
  darkMode: "class",
  // Accent dark-mode backgrounds used across components
  // (tailwind jit arbitrary values already scan TS files, safelist not strictly needed)
  theme: {
    extend: {
      colors: {
        "surface-tint": "#3c5d9c",
        surface: "#faf9ff",
        "surface-dim": "#dad9df",
        "surface-bright": "#faf9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f9",
        "surface-container": "#eeedf3",
        "surface-container-high": "#e8e7ed",
        "surface-container-highest": "#e3e2e8",
        "surface-variant": "#e3e2e8",
        "on-surface": "#1a1b20",
        "on-surface-variant": "#434750",
        "inverse-surface": "#2f3035",
        "inverse-on-surface": "#f1f0f6",
        primary: "#001b44",
        "on-primary": "#ffffff",
        "primary-container": "#002f6c",
        "on-primary-container": "#7999dc",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#aec6ff",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#224583",
        "inverse-primary": "#aec6ff",
        secondary: "#006971",
        "on-secondary": "#ffffff",
        "secondary-container": "#76f1ff",
        "on-secondary-container": "#006d76",
        "secondary-fixed": "#87f3ff",
        "secondary-fixed-dim": "#59d8e5",
        "on-secondary-fixed": "#001f23",
        "on-secondary-fixed-variant": "#004f55",
        tertiary: "#43000d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6a001a",
        "on-tertiary-container": "#ff6675",
        "tertiary-fixed": "#ffdada",
        "tertiary-fixed-dim": "#ffb3b5",
        "on-tertiary-fixed": "#40000c",
        "on-tertiary-fixed-variant": "#920027",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        outline: "#747781",
        "outline-variant": "#c4c6d2",
        background: "#faf9ff",
        "on-background": "#1a1b20",
        // Accent colors from design
        accent: {
          green: "#00FF9D",
          pink: "#FF2D55",
          coral: "#FF6675",
        },
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
