# Generated by Django 5.2.12 on 2026-04-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweasy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(help_text='Напр. "01"', max_length=10, verbose_name='Номер')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('bg', models.CharField(choices=[('bg-[#FF2D55]', '🔴 Красный (#FF2D55)'), ('bg-[#FF6675]', '🌸 Коралловый (#FF6675)'), ('bg-[#00FF9D]', '🟢 Зелёный (#00FF9D)'), ('bg-[#229ED9]', '🔵 Telegram синий (#229ED9)'), ('bg-primary', '🫐 Тёмно-синий (primary)'), ('bg-primary-container', '💙 Синий светлый (primary-container)'), ('bg-tertiary-container', '🟣 Третичный (tertiary-container)')], default='bg-primary-container', max_length=100, verbose_name='Фон карточки')),
                ('num_color', models.CharField(choices=[('text-[#FF2D55]', '🔴 Красный'), ('text-[#00FF9D]', '🟢 Зелёный'), ('text-primary', '🫐 Тёмно-синий'), ('text-white', 'Белый')], default='text-[#FF2D55]', max_length=100, verbose_name='Цвет номера')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Факт',
                'verbose_name_plural': 'Факты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('bg', models.CharField(choices=[('bg-[#FF2D55]', '🔴 Красный (#FF2D55)'), ('bg-[#FF6675]', '🌸 Коралловый (#FF6675)'), ('bg-[#00FF9D]', '🟢 Зелёный (#00FF9D)'), ('bg-[#229ED9]', '🔵 Telegram синий (#229ED9)'), ('bg-primary', '🫐 Тёмно-синий (primary)'), ('bg-primary-container', '💙 Синий светлый (primary-container)'), ('bg-tertiary-container', '🟣 Третичный (tertiary-container)')], default='bg-[#FF2D55]', max_length=100, verbose_name='Фон')),
                ('color', models.CharField(choices=[('text-white', 'Белый'), ('text-primary', 'Тёмно-синий')], default='text-white', max_length=100, verbose_name='Цвет текста')),
                ('rotate', models.CharField(blank=True, choices=[('', 'Без наклона'), ('-rotate-2', '−2°'), ('-rotate-1', '−1°'), ('rotate-1', '+1°'), ('rotate-2', '+2°')], default='', max_length=50, verbose_name='Наклон')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Бейдж Hero',
                'verbose_name_plural': 'Бейджи Hero',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(help_text='Напр. /media/photo.jpg', max_length=500, verbose_name='URL изображения')),
                ('image_upload', models.ImageField(blank=True, help_text='Загрузка перекрывает URL выше', null=True, upload_to='uploads/posts/', verbose_name='Или загрузить файл')),
                ('alt', models.CharField(max_length=300, verbose_name='Alt текст')),
                ('caption', models.CharField(max_length=300, verbose_name='Подпись')),
                ('badge_text', models.CharField(max_length=200, verbose_name='Текст бейджа')),
                ('badge_bg', models.CharField(choices=[('bg-[#FF2D55]', '🔴 Красный (#FF2D55)'), ('bg-[#FF6675]', '🌸 Коралловый (#FF6675)'), ('bg-[#00FF9D]', '🟢 Зелёный (#00FF9D)'), ('bg-[#229ED9]', '🔵 Telegram синий (#229ED9)'), ('bg-primary', '🫐 Тёмно-синий (primary)'), ('bg-primary-container', '💙 Синий светлый (primary-container)'), ('bg-tertiary-container', '🟣 Третичный (tertiary-container)')], default='bg-[#FF2D55]', max_length=100, verbose_name='Фон бейджа')),
                ('badge_color', models.CharField(choices=[('text-white', 'Белый'), ('text-primary', 'Тёмно-синий')], default='text-white', max_length=100, verbose_name='Цвет текста бейджа')),
                ('badge_rotate', models.CharField(blank=True, choices=[('', 'Без наклона'), ('-rotate-2', '−2°'), ('-rotate-1', '−1°'), ('rotate-1', '+1°'), ('rotate-2', '+2°')], default='', max_length=50, verbose_name='Наклон бейджа')),
                ('offset', models.BooleanField(default=False, verbose_name='Сдвинуть вниз (offset)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Пост (лента)',
                'verbose_name_plural': 'Посты (лента)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Sweasy', max_length=100, verbose_name='Название бренда')),
                ('copyright', models.CharField(default='© 2024 Sweasy. Все права защищены.', max_length=300, verbose_name='Копирайт')),
                ('mood_label', models.CharField(default='Настроение', max_length=100, verbose_name='Лейбл настроения')),
                ('mood_status', models.CharField(default='ОТКРЫТА ГОРИЗОНТАМ — ЖИВЁМ НА ПРИВЫСОКОЙ НОТЕ', max_length=300, verbose_name='Статус (бегущая строка)')),
                ('hero_image_url', models.CharField(default='/media/CYWp61nNVxe_4k.jpg', help_text='Путь к изображению, напр. /media/image.jpg', max_length=500, verbose_name='URL фото hero')),
                ('hero_subtitle', models.TextField(default='Проводим тебя туда, где реальность сливается с волшебством.', verbose_name='Подзаголовок hero')),
                ('live_feed_title', models.CharField(default='СВЕЖИЕ ВПЕЧАТЛЕНИЯ', max_length=200, verbose_name='Заголовок ленты')),
                ('live_feed_subtitle', models.CharField(default='Пульс Швейцарии — наши лучшие моменты прямо сейчас', max_length=300, verbose_name='Подзаголовок ленты')),
                ('tours_title', models.CharField(default='АВТОРСКИЕ ТУРЫ', max_length=200, verbose_name='Заголовок туров')),
                ('tours_subtitle', models.CharField(default='Твои маршруты к лучшему в Швейцарии', max_length=300, verbose_name='Подзаголовок туров')),
                ('facts_title', models.CharField(default='ФАКТЫ, КОТОРЫЕ МЫ ПРОЖИВАЕМ', max_length=200, verbose_name='Заголовок фактов')),
                ('facts_subtitle', models.CharField(default='Открывай Швейцарию снутри — глазами локального гида', max_length=300, verbose_name='Подзаголовок фактов')),
                ('cta_headline', models.CharField(default='ВПЕРЕД, В ТВОЮ ШВЕЙЦАРИЮ — ЗАПИШИСЬ НА ТУР!', max_length=300, verbose_name='Заголовок CTA')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_url', models.CharField(help_text='Напр. /media/photo.jpg', max_length=500, verbose_name='URL изображения')),
                ('image_upload', models.ImageField(blank=True, help_text='Загрузка перекрывает URL выше', null=True, upload_to='uploads/tours/', verbose_name='Или загрузить файл')),
                ('badge_text', models.CharField(max_length=200, verbose_name='Текст бейджа')),
                ('badge_bg', models.CharField(choices=[('bg-[#FF2D55]', '🔴 Красный (#FF2D55)'), ('bg-[#FF6675]', '🌸 Коралловый (#FF6675)'), ('bg-[#00FF9D]', '🟢 Зелёный (#00FF9D)'), ('bg-[#229ED9]', '🔵 Telegram синий (#229ED9)'), ('bg-primary', '🫐 Тёмно-синий (primary)'), ('bg-primary-container', '💙 Синий светлый (primary-container)'), ('bg-tertiary-container', '🟣 Третичный (tertiary-container)')], default='bg-[#FF2D55]', max_length=100, verbose_name='Фон бейджа')),
                ('badge_color', models.CharField(choices=[('text-white', 'Белый'), ('text-primary', 'Тёмно-синий')], default='text-white', max_length=100, verbose_name='Цвет текста бейджа')),
                ('badge_rotate', models.CharField(blank=True, choices=[('', 'Без наклона'), ('-rotate-2', '−2°'), ('-rotate-1', '−1°'), ('rotate-1', '+1°'), ('rotate-2', '+2°')], default='', max_length=50, verbose_name='Наклон бейджа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='pagesnapshot',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at'], 'verbose_name': 'Снапшот (AI)', 'verbose_name_plural': 'Снапшоты (AI)'},
        ),
    ]
