# Generated by Django 4.1.7 on 2023-10-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("duration", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_participants", models.IntegerField()),
                ("guide_name", models.CharField(max_length=50)),
                ("meeting_point", models.CharField(max_length=100)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
    ]
