# Generated by Django 4.1.7 on 2023-10-03 14:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
