"""Pydantic models for AI-generated page configuration.

Each model corresponds to a React component. The AI fills these
via Structured Output based on Instagram content analysis.
"""
from __future__ import annotations

from pydantic import BaseModel, Field


# ── UI Primitives ──


class BadgeConfig(BaseModel):
    text: str
    bg: str = Field(description="Tailwind bg class, e.g. 'bg-[#FF2D55]'")
    color: str = Field(description="Tailwind text color class, e.g. 'text-white'")
    rotate: str = Field(default="", description="Tailwind rotate class, e.g. '-rotate-2'")


class PostCardConfig(BaseModel):
    image_url: str = Field(description="URL or local path to post image")
    alt: str = Field(description="Image alt text, short")
    caption: str = Field(description="Short punchy caption for the card, uppercase style")
    badge: BadgeConfig
    offset: bool = Field(default=False, description="Vertical offset for masonry effect")


class FactCardConfig(BaseModel):
    num: str = Field(description="Two-digit number like '01'")
    title: str = Field(description="Bold headline, can contain newline")
    text: str = Field(description="Supporting paragraph")
    bg: str = Field(description="Tailwind bg class for card background")
    num_color: str = Field(description="Tailwind text color for the number", serialization_alias="numColor")


# ── Layout Components ──


class MoodBarConfig(BaseModel):
    label: str = Field(default="AI Mood of the Week", description="Left side label")
    status: str = Field(description="Right side mood status text, punchy and short")


class NavbarConfig(BaseModel):
    brand: str = Field(default="Stan Live")


class FooterConfig(BaseModel):
    brand: str = Field(default="Stan Live")
    copyright: str = Field(default="© 2024 Stan Live. Swiss Precision Branding.")


# ── Page Sections ──


class HeroConfig(BaseModel):
    image_url: str = Field(description="Hero background image URL")
    badges: list[BadgeConfig] = Field(description="1-3 overlapping badge labels")
    subtitle: str = Field(description="Short paragraph about the guide/brand")


class LiveFeedConfig(BaseModel):
    title: str = Field(default="Live\nFeed")
    subtitle: str = Field(default="Real-time Swiss Stories")
    posts: list[PostCardConfig] = Field(description="4 post cards for the feed grid")


class FactsConfig(BaseModel):
    title: str = Field(default="Swiss Intelligence")
    subtitle: str = Field(default="Essential facts for the modern traveler")
    facts: list[FactCardConfig] = Field(description="Exactly 9 fact cards based on Instagram content and Swiss topics")


class TourCardConfig(BaseModel):
    title: str = Field(description="Tour name, short and punchy")
    description: str = Field(description="1-2 sentence tour description")
    image_url: str = Field(description="Image path for the tour card")
    badge: BadgeConfig


class ToursConfig(BaseModel):
    title: str = Field(default="НАШИ ТУРЫ")
    subtitle: str = Field(default="Авторские маршруты по Швейцарии")
    tours: list[TourCardConfig] = Field(description="Exactly 3 tour cards")


class CTAConfig(BaseModel):
    headline: str = Field(description="Big punchy headline, uppercase")


# ── Root Model ──


class PageConfig(BaseModel):
    """Complete page configuration generated by AI from Instagram content."""
    navbar: NavbarConfig = Field(default_factory=NavbarConfig)
    mood_bar: MoodBarConfig
    hero: HeroConfig
    live_feed: LiveFeedConfig
    tours: ToursConfig
    facts: FactsConfig
    cta: CTAConfig
    footer: FooterConfig = Field(default_factory=FooterConfig)
